In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')  

from urllib.request import urlopen

pd.set_option('display.max_columns', None)

In [2]:
# EXPLORACIÓN DE ARCHVIVOS. 1º ACTOR

In [3]:
d_actor = pd.read_csv('actor.csv') # EXPLORACIÓN DE ARCHVIVOS. 1º ACTOR

In [4]:
d_actor1 = d_actor.copy() # Creo una copia del df por si me equivoco con la limpieza de datos

In [5]:
d_actor.shape # Es un archivo que contiene 200 filas y 4 columnas

(200, 3)

In [6]:
d_actor.columns # Nombre de las columnas de mi archivo

Index(['actor_id', 'first_name', 'last_name'], dtype='object')

In [7]:
d_actor.duplicated().any() # No tenemos duplicados

False

In [8]:
nan_cols = d_actor.isna().mean() * 100   #porcentaje de nulos por columna. Cero nulos.Alegría
nan_cols

actor_id      0.0
first_name    0.0
last_name     0.0
dtype: float64

In [9]:
d_actor.dtypes # tipo de datos por columna

actor_id       int64
first_name    object
last_name     object
dtype: object

In [ ]:
d_actor.last_update.sample(n=7) # last_update no aporta ninguna info relevante. La voy a borrar

In [ ]:
d_actor.drop(columns=['last_update'], inplace=True) # Borro la columna last_update
d_actor.columns

In [13]:
d_actor.columns

Index(['actor_id', 'first_name', 'last_name'], dtype='object')

In [16]:
# El archvivo se lee y entiende bien. No hace falta explorar más ni llevar a cabo más limpieza de datos.

In [17]:
d_actor.to_csv('actor.csv', index=False) # Guardo el csv final. Fin con la exploración y cleaning de actor.

In [39]:
# EXPLORACIÓN DE ARCHVIVOS. 2º CATEGORY

In [40]:
d_category = pd.read_csv('category.csv')

In [41]:
d_category2 = d_category.copy() # Creo una copia del df por si me equivoco con la limpieza de datos

In [42]:
d_category.head(6) # Primer vistazo del archivo

category_id         name          last_update
0            1       Action  2006-02-15 04:46:27
1            2    Animation  2006-02-15 04:46:27
2            3     Children  2006-02-15 04:46:27
3            4     Classics  2006-02-15 04:46:27
4            5       Comedy  2006-02-15 04:46:27
5            6  Documentary  2006-02-15 04:46:27

In [43]:
d_category.shape # Es un archivo con 16 filas y 3 columnas

(16, 3)

In [44]:
d_category.duplicated().any() # No hay duplicados

False

In [45]:
d_category.name.unique() #Los valores unico de la columna name

array(['Action', 'Animation', 'Children', 'Classics', 'Comedy',
       'Documentary', 'Drama', 'Family', 'Foreign', 'Games', 'Horror',
       'Music', 'New', 'Sci-Fi', 'Sports', 'Travel'], dtype=object)

In [46]:
# last_update en este archivo tampoco me aporta nada relevante. La voy a eliminar

In [47]:
d_category.drop(columns=['last_update'], inplace=True) # Borro la columna last_update
d_category.columns

Index(['category_id', 'name'], dtype='object')

In [48]:
d_category.shape, d_category2.shape # comparación dimensiones df actual vs original

((16, 2), (16, 3))

In [50]:
nan_cols = d_category.isna().mean() * 100   #porcentaje de nulos por columna. Cero nulos. +Alegría
nan_cols

category_id    0.0
name           0.0
dtype: float64

In [51]:
d_category.dtypes # Ok al tipo de dato

category_id     int64
name           object
dtype: object

In [52]:
d_category.to_csv('category.csv', index=False) # Guardo el csv final. Fin con la exploración y cleaning de category.

In [53]:
# EXPLORACIÓN DE ARCHVIVOS. 3º FILM

In [54]:
d_pelis = pd.read_csv('film.csv')

In [57]:
d_pelis2 = d_pelis.copy()

In [63]:
d_pelis.head(5) # Observo bien el contenido.

film_id             title  \
0        1  ACADEMY DINOSAUR   
1        2    ACE GOLDFINGER   
2        3  ADAPTATION HOLES   
3        4  AFFAIR PREJUDICE   
4        5       AFRICAN EGG   

                                         description  release_year  \
0  A Epic Drama of a Feminist And a Mad Scientist...          2006   
1  A Astounding Epistle of a Database Administrat...          2006   
2  A Astounding Reflection of a Lumberjack And a ...          2006   
3  A Fanciful Documentary of a Frisbee And a Lumb...          2006   
4  A Fast-Paced Documentary of a Pastry Chef And ...          2006   

   language_id  original_language_id  rental_duration  rental_rate  length  \
0            1                   NaN                6         0.99      86   
1            1                   NaN                3         4.99      48   
2            1                   NaN                7         2.99      50   
3            1                   NaN                5         2.99     117   
4            1                   NaN                6         2.99     130   

   replacement_cost rating                  special_features  \
0             20.99     PG  Deleted Scenes,Behind the Scenes   
1             12.99      G           Trailers,Deleted Scenes   
2             18.99  NC-17           Trailers,Deleted Scenes   
3             26.99      G    Commentaries,Behind the Scenes   
4             22.99      G                    Deleted Scenes   

           last_update  
0  2006-02-15 05:03:42  
1  2006-02-15 05:03:42  
2  2006-02-15 05:03:42  
3  2006-02-15 05:03:42  
4  2006-02-15 05:03:42

In [55]:
d_pelis.shape # aquí tenemos 1000 filas y 13 columnas

(1000, 13)

In [56]:
d_pelis.columns # nombre de las columnas

Index(['film_id', 'title', 'description', 'release_year', 'language_id',
       'original_language_id', 'rental_duration', 'rental_rate', 'length',
       'replacement_cost', 'rating', 'special_features', 'last_update'],
      dtype='object')

In [58]:
d_pelis.duplicated().any() # No hay duplicados

False

In [62]:
d_pelis.dtypes

film_id                   int64
title                    object
description              object
release_year              int64
language_id               int64
original_language_id    float64
rental_duration           int64
rental_rate             float64
length                    int64
replacement_cost        float64
rating                   object
special_features         object
last_update              object
dtype: object

In [64]:
nan_cols = d_pelis.isna().mean() * 100   #porcentaje de nulos por columna. 100% de nulos en original_languaje_id.
nan_cols

film_id                   0.0
title                     0.0
description               0.0
release_year              0.0
language_id               0.0
original_language_id    100.0
rental_duration           0.0
rental_rate               0.0
length                    0.0
replacement_cost          0.0
rating                    0.0
special_features          0.0
last_update               0.0
dtype: float64

In [65]:
d_pelis.drop(columns=['original_language_id'], inplace=True) # Borro original_languaje_id
d_pelis.columns

Index(['film_id', 'title', 'description', 'release_year', 'language_id',
       'rental_duration', 'rental_rate', 'length', 'replacement_cost',
       'rating', 'special_features', 'last_update'],
      dtype='object')

In [66]:
d_pelis.drop(columns=['last_update'], inplace=True) # Borro last_update como en los archivos anteriores
d_pelis.columns

Index(['film_id', 'title', 'description', 'release_year', 'language_id',
       'rental_duration', 'rental_rate', 'length', 'replacement_cost',
       'rating', 'special_features'],
      dtype='object')

In [67]:
d_pelis.dtypes # reviso de nuevo el tipo de dato en cada columna

film_id               int64
title                object
description          object
release_year          int64
language_id           int64
rental_duration       int64
rental_rate         float64
length                int64
replacement_cost    float64
rating               object
special_features     object
dtype: object

In [70]:
d_pelis.title.sample(n=8) # breve vistazo a la columna title

955        WANDA CHAMBER
658         PARK CITIZEN
375          GRAPES FURY
89         BOULEVARD MOB
937    VELVET TERMINATOR
468            IRON MOON
773       SEARCHERS WAIT
259       DUDE BLINDNESS
Name: title, dtype: object

In [71]:
d_pelis.description.sample(n=8) # parece que hay un problema de caligrafía con tanta mayúscula, pero no le voy a dar
                                # más importancia.

573    A Taut Reflection of a Husband And a A Shark w...
416    A Epic Display of a Hunter And a Feminist who ...
988    A Stunning Epistle of a Dentist And a Dog who ...
815    A Fateful Display of a Lumberjack And a Girl w...
334    A Emotional Reflection of a Dentist And a Mad ...
40     A Fanciful Documentary of a Mad Cow And a Woma...
657    A Intrepid Story of a Squirrel And a Crocodile...
759    A Fast-Paced Story of a Pioneer And a Astronau...
Name: description, dtype: object

In [83]:
d_pelis.release_year.sample(n=6) # poca info. Veamos sus valores únicos no vaya a ser ....

727    2006
115    2006
999    2006
175    2006
77     2006
254    2006
Name: release_year, dtype: int64

In [84]:
d_pelis.release_year.unique() # Son todo pelis del 2006. Voy a borrar esta columna.

array([2006])

In [85]:
d_pelis.drop(columns=['release_year'], inplace=True)
d_pelis.columns

Index(['film_id', 'title', 'description', 'language_id', 'rental_duration',
       'rental_rate', 'length', 'replacement_cost', 'rating',
       'special_features'],
      dtype='object')

In [86]:
d_pelis.rental_duration.sample(n=6)

221    4
67     5
955    7
509    6
237    4
146    5
Name: rental_duration, dtype: int64

In [87]:
d_pelis.rental_duration.unique() # ¿Qué significa este dato? Duración del alquiler

array([6, 3, 7, 5, 4])

In [88]:
d_pelis.head()

film_id             title  \
0        1  ACADEMY DINOSAUR   
1        2    ACE GOLDFINGER   
2        3  ADAPTATION HOLES   
3        4  AFFAIR PREJUDICE   
4        5       AFRICAN EGG   

                                         description  language_id  \
0  A Epic Drama of a Feminist And a Mad Scientist...            1   
1  A Astounding Epistle of a Database Administrat...            1   
2  A Astounding Reflection of a Lumberjack And a ...            1   
3  A Fanciful Documentary of a Frisbee And a Lumb...            1   
4  A Fast-Paced Documentary of a Pastry Chef And ...            1   

   rental_duration  rental_rate  length  replacement_cost rating  \
0                6         0.99      86             20.99     PG   
1                3         4.99      48             12.99      G   
2                7         2.99      50             18.99  NC-17   
3                5         2.99     117             26.99      G   
4                6         2.99     130             22.99      G   

                   special_features  
0  Deleted Scenes,Behind the Scenes  
1           Trailers,Deleted Scenes  
2           Trailers,Deleted Scenes  
3    Commentaries,Behind the Scenes  
4                    Deleted Scenes

In [90]:
d_pelis.rental_rate.unique() # coste de alquilar la peli. Los precios varían entre 3 valores unicos

array([0.99, 4.99, 2.99])

In [91]:
d_pelis.replacement_cost.unique() # coste de compra de la pelicula

array([20.99, 12.99, 18.99, 26.99, 22.99, 17.99, 28.99, 15.99, 21.99,
       24.99, 16.99, 23.99, 10.99, 14.99, 27.99,  9.99, 19.99, 11.99,
       29.99, 25.99, 13.99])

In [ ]:
# no voy a cambiar los nombres de la columnas por las relaciones que haya con el archivo rental.csv  

In [ ]:
# He explorado y entendido bien la tabla de film y que información me aporta en cada una de sus columnas.
# Voy a guardarlo

In [92]:
d_pelis.to_csv('film.csv', index=False) # Guardo csv final

In [ ]:
# EXPLORACIÓN DE ARCHVIVOS. 4º INVENTORY

In [93]:
d_inventory = pd.read_csv('inventory.csv')

In [94]:
d_inventory2=d_inventory.copy()

In [97]:
d_inventory.shape

(1000, 4)

In [98]:
d_inventory.head(7)

inventory_id  film_id  store_id          last_update
0             1        1         1  2006-02-15 05:09:17
1             2        1         1  2006-02-15 05:09:17
2             3        1         1  2006-02-15 05:09:17
3             4        1         1  2006-02-15 05:09:17
4             5        1         2  2006-02-15 05:09:17
5             6        1         2  2006-02-15 05:09:17
6             7        1         2  2006-02-15 05:09:17

In [99]:
d_inventory.columns

Index(['inventory_id', 'film_id', 'store_id', 'last_update'], dtype='object')

In [100]:
d_inventory.duplicated().any()

False

In [101]:
nan_cols = d_inventory.isna().mean() * 100   #porcentaje de nulos por columna. 100% de nulos en original_languaje_id.
nan_cols

inventory_id    0.0
film_id         0.0
store_id        0.0
last_update     0.0
dtype: float64

In [104]:
d_inventory.dtypes

inventory_id     int64
film_id          int64
store_id         int64
last_update     object
dtype: object

In [106]:
d_inventory.last_update.unique()

array(['2006-02-15 05:09:17'], dtype=object)

In [107]:
d_inventory.drop(columns=['last_update'], inplace=True)
d_inventory.columns

Index(['inventory_id', 'film_id', 'store_id'], dtype='object')

In [110]:
d_inventory.store_id.unique()

array([1, 2])

In [114]:
d_inventory.film_id.unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  34,  35,  37,  39,  40,  42,  43,  44,
        45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
        58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
        71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
        84,  85,  86,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
        98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 109, 110, 111,
       112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124,
       125, 126, 127, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 145, 146, 147, 149, 150, 151, 152, 153,
       154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
       167, 168, 169, 170, 172, 173, 174, 175, 176, 177, 178, 179, 180,
       181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 19

In [117]:
d_inventory.to_csv('inventory.csv', index=False) # Guardo csv final

In [ ]:
# EXPLORACIÓN DE ARCHVIVOS. 5º LENGUAGE

In [119]:
d_language = pd.read_csv('language.csv')

In [120]:
d_language.shape # solo 6 filas y 3 columnas

(6, 3)

In [121]:
d_language # solo hay que borrar last_update

language_id      name          last_update
0            1   English  2006-02-15 05:02:19
1            2   Italian  2006-02-15 05:02:19
2            3  Japanese  2006-02-15 05:02:19
3            4  Mandarin  2006-02-15 05:02:19
4            5    French  2006-02-15 05:02:19
5            6    German  2006-02-15 05:02:19

In [122]:
d_language.drop(columns=['last_update'], inplace=True)
d_language.columns

Index(['language_id', 'name'], dtype='object')

In [123]:
d_language.to_csv('language.csv', index=False) # Guardo csv final

In [ ]:
# EXPLORACIÓN DE ARCHVIVOS. 6º OLD_HDD

In [124]:
d_old = pd.read_csv('OLD_HDD.csv')

In [125]:
d_old.shape

(1000, 5)

In [126]:
d_old.columns

Index(['first_name', 'last_name', 'title', 'release_year', 'category_id'], dtype='object')

In [127]:
d_old.head()

first_name last_name                  title  release_year  category_id
0   PENELOPE   GUINESS       ACADEMY DINOSAUR          2006            6
1   PENELOPE   GUINESS   ANACONDA CONFESSIONS          2006            2
2   PENELOPE   GUINESS            ANGELS LIFE          2006           13
3   PENELOPE   GUINESS  BULWORTH COMMANDMENTS          2006           10
4   PENELOPE   GUINESS          CHEAPER CLYDE          2006           14

In [128]:
d_old.first_name.unique()

array(['PENELOPE', 'NICK', 'ED', 'JENNIFER', 'JOHNNY', 'BETTE', 'GRACE',
       'MATTHEW', 'JOE', 'CHRISTIAN', 'ZERO', 'KARL', 'UMA', 'VIVIEN',
       'CUBA', 'FRED', 'HELEN', 'DAN', 'BOB', 'LUCILLE', 'KIRSTEN',
       'ELVIS', 'SANDRA', 'CAMERON', 'KEVIN', 'RIP', 'JULIA', 'WOODY',
       'ALEC', 'SISSY', 'TIM', 'MILLA', 'AUDREY', 'JUDY', 'BURT', 'VAL',
       'TOM', 'GOLDIE'], dtype=object)

In [146]:
d_old.first_name.value_counts() # numero de titulos en los que aparece cada actor

SANDRA       56
VAL          35
UMA          35
JULIA        33
RIP          33
HELEN        32
KARL         31
WOODY        31
VIVIEN       30
LUCILLE      30
GRACE        30
JOHNNY       29
BURT         29
ALEC         29
CUBA         28
KIRSTEN      27
FRED         27
ELVIS        26
ZERO         25
BOB          25
NICK         25
AUDREY       25
JOE          25
TOM          25
MILLA        24
CAMERON      24
TIM          23
DAN          22
ED           22
JENNIFER     22
CHRISTIAN    22
KEVIN        21
MATTHEW      20
BETTE        20
PENELOPE     19
SISSY        18
JUDY         15
GOLDIE        7
Name: first_name, dtype: int64

In [129]:
d_old.release_year.unique()

array([2006])

In [130]:
d_old.drop(columns=['release_year'], inplace=True)
d_old.columns

Index(['first_name', 'last_name', 'title', 'category_id'], dtype='object')

In [147]:
d_old.isnull().any() # No tenemos nulos

first_name     False
last_name      False
title          False
category_id    False
dtype: bool

In [148]:
d_old.to_csv('OLD_HDD.csv', index=False) # Guardo csv final

In [ ]:
# EXPLORACIÓN DE ARCHVIVOS. 6º RENTAL

In [149]:
d_rental = pd.read_csv('rental.csv')

In [150]:
d_rental.shape # 1000 filas 7 columnas

(1000, 7)

In [155]:
d_rental.columns

Index(['rental_id', 'rental_date', 'inventory_id', 'customer_id',
       'return_date', 'staff_id', 'last_update'],
      dtype='object')

In [ ]:
d_rental.drop(columns=['last_update'], inplace=True) #borro last_update por la misma razón que en las anteriores

In [164]:
d_rental.head(7)

rental_id          rental_date  inventory_id  customer_id  \
0          1  2005-05-24 22:53:30           367          130   
1          2  2005-05-24 22:54:33          1525          459   
2          3  2005-05-24 23:03:39          1711          408   
3          4  2005-05-24 23:04:41          2452          333   
4          5  2005-05-24 23:05:21          2079          222   
5          6  2005-05-24 23:08:07          2792          549   
6          7  2005-05-24 23:11:53          3995          269   

           return_date  staff_id  
0  2005-05-26 22:04:30         1  
1  2005-05-28 19:40:33         1  
2  2005-06-01 22:12:39         1  
3  2005-06-03 01:43:41         2  
4  2005-06-02 04:33:21         1  
5  2005-05-27 01:32:07         1  
6  2005-05-29 20:34:53         2

In [159]:
d_rental.isnull().any() # ningún valor nulo en las columnas

rental_id       False
rental_date     False
inventory_id    False
customer_id     False
return_date     False
staff_id        False
dtype: bool

In [163]:
d_rental.return_date.head()

0    2005-05-26 22:04:30
1    2005-05-28 19:40:33
2    2005-06-01 22:12:39
3    2005-06-03 01:43:41
4    2005-06-02 04:33:21
Name: return_date, dtype: object

In [166]:
d_rental.rental_id.info()

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: rental_id
Non-Null Count  Dtype
--------------  -----
1000 non-null   int64
dtypes: int64(1)
memory usage: 7.9 KB


In [167]:
d_rental.to_csv('rental.csv', index=False) # Guardo csv final

In [ ]:
#FIN DEL DATA CLEANING

In [ ]:
# CREAR BASE DE DATOS Y ALIMENTARLA

In [180]:
%pip install SQLAlchemy

Note: you may need to restart the kernel to use updated packages.


In [181]:
%pip install pymysql

     |████████████████████████████████| 43 kB 2.7 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [170]:
import mysql.connector as conn

In [182]:
from sqlalchemy import create_engine

In [183]:
# crear una base de datos

# string de conexion URI
# lenguaje+driver://usuario:password@servidor:puerto

str_conn='mysql+pymysql://root:password@localhost:3306'

cursor=create_engine(str_conn)


cursor.execute('create database VIDEOCLUB;')         #CREO LA BASE DE DATOS "VIDEOCLUB"

In [186]:
str_conn='mysql+pymysql://root:password@localhost:3306/VIDEOCLUB'

cursor=create_engine(str_conn)

In [187]:
d_actor.to_sql(name='actor', con=cursor, if_exists='replace', index=False) # AÑADO ACTOR

200

In [188]:
d_category.to_sql(name='category', con=cursor, if_exists='replace', index=False) # AÑADO CATEGORY

16

In [189]:
d_pelis.to_sql(name='film', con=cursor, if_exists='replace', index=False) # AÑADO FILM

1000

In [190]:
d_inventory.to_sql(name='inventory', con=cursor, if_exists='replace', index=False) # AÑADO INVENTORY

1000

In [191]:
d_language.to_sql(name='language', con=cursor, if_exists='replace', index=False) # AÑADO LANGUAGE

6

In [192]:
d_old.to_sql(name='old_hdd', con=cursor, if_exists='replace', index=False) # AÑADO OLD_HDD

1000

In [193]:
d_rental.to_sql(name='rental', con=cursor, if_exists='replace', index=False) # AÑADO RENTAL

1000

In [194]:
cursor.execute('alter table actor add primary key (actor_id);') # PRIMARY KEY DE ACTOR

In [196]:
cursor.execute('alter table category add primary key (category_id);') #PRIMARY KEY DE CATEGORY

In [197]:
cursor.execute('alter table film add primary key (film_id);') # PRIMARY CATEGORY DE FILM

In [198]:
cursor.execute('alter table inventory add primary key (inventory_id);') # PRIMARY KEY DE INVENTORY

In [199]:
cursor.execute('alter table language add primary key (language_id);') # PRIMARY KEY DE LANGUAGE

In [200]:
cursor.execute('alter table rental add primary key (rental_id);') # PRIMARY KEY DE RENTAL